// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbH7Krx9QMCzdx-fk4Uy3xsoHVOyuT60',
    appId: '1:1002486189975:web:0f1e982185b23996d23ed2',
    messagingSenderId: '1002486189975',
    projectId: 'etravelers-4303a',
    authDomain: 'etravelers-4303a.firebaseapp.com',
    storageBucket: 'etravelers-4303a.firebasestorage.app',
    measurementId: 'G-D3MH9FM5YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnvl4fnMXQamf9c8OQUA79PfUQZ--I2k',
    appId: '1:1002486189975:android:fdcf29c5978a5bd2d23ed2',
    messagingSenderId: '1002486189975',
    projectId: 'etravelers-4303a',
    storageBucket: 'etravelers-4303a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1P-qaIr6TlxyIMuTPgbGYR1XzfMgZa6E',
    appId: '1:1002486189975:ios:a425626974f9adecd23ed2',
    messagingSenderId: '1002486189975',
    projectId: 'etravelers-4303a',
    storageBucket: 'etravelers-4303a.firebasestorage.app',
    iosBundleId: 'com.example.eTraverlers',
  );
}
